In [2]:
import lancedb
from constance import KNOWLEDGE_BASE_PATH


vector_db = lancedb.connect(KNOWLEDGE_BASE_PATH)
vector_db

LanceDBConnection(uri='c:\\Users\\alici\\moln_mlpos\\code_along_moln_repo\\lecktion_6\\knowled_base')

In [3]:
import json

with open("animals_text_embeddings.json") as file:
    data = json.load(file)

data

[{'text': 'A small brown dog running.', 'vector': [0.12, 0.85, 0.33]},
 {'text': 'A cat resting quietly on a sofa.', 'vector': [0.4, 0.91, 0.1]},
 {'text': 'A large gray elephant drinking water.',
  'vector': [0.88, 0.22, 0.55]},
 {'text': 'A fast cheetah sprinting across the savannah.',
  'vector': [0.95, 0.12, 0.72]},
 {'text': 'A colorful parrot perched on a branch.',
  'vector': [0.25, 0.66, 0.81]},
 {'text': 'A frog sitting on a lily pad.', 'vector': [0.14, 0.44, 0.27]}]

In [4]:
vector_db.create_table("animals_text", exist_ok=True, data=data)
vector_db["animals_text"]

LanceTable(name='animals_text', version=1, _conn=LanceDBConnection(uri='c:\\Users\\alici\\moln_mlpos\\code_along_moln_repo\\lecktion_6\\knowled_base'))

In [5]:
vector_db["animals_text"].to_pandas()

                                            text              vector
0                     A small brown dog running.  [0.12, 0.85, 0.33]
1               A cat resting quietly on a sofa.    [0.4, 0.91, 0.1]
2          A large gray elephant drinking water.  [0.88, 0.22, 0.55]
3  A fast cheetah sprinting across the savannah.  [0.95, 0.12, 0.72]
4         A colorful parrot perched on a branch.  [0.25, 0.66, 0.81]
5                  A frog sitting on a lily pad.  [0.14, 0.44, 0.27]

In [8]:
more_data = [
    {"text": "A panda eating bamboo peacefully.", "vector": [0.51, 0.37, 0.82]},
    {"text": "A lion roaring loudly on a rock.", "vector": [0.93, 0.18, 0.41]},
]

vector_db["animals_text"].add(more_data)

AddResult(version=2)

In [9]:
vector_db["animals_text"].to_pandas()

                                            text              vector
0                     A small brown dog running.  [0.12, 0.85, 0.33]
1               A cat resting quietly on a sofa.    [0.4, 0.91, 0.1]
2          A large gray elephant drinking water.  [0.88, 0.22, 0.55]
3  A fast cheetah sprinting across the savannah.  [0.95, 0.12, 0.72]
4         A colorful parrot perched on a branch.  [0.25, 0.66, 0.81]
5                  A frog sitting on a lily pad.  [0.14, 0.44, 0.27]
6              A panda eating bamboo peacefully.  [0.51, 0.37, 0.82]
7               A lion roaring loudly on a rock.  [0.93, 0.18, 0.41]

In [11]:
from lancedb.pydantic import LanceModel

class Aricel(LanceModel):
    title: str
    content: str

vector_db.create_table("articals", schema = Aricel, exist_ok=True)

LanceTable(name='articals', version=1, _conn=LanceDBConnection(uri='c:\\Users\\alici\\moln_mlpos\\code_along_moln_repo\\lecktion_6\\knowled_base'))

In [12]:
vector_db.list_tables()

ListTablesResponse(tables=['animals_text', 'articals'], page_token=None)

In [17]:
articles_data = [
    {
        "title": "Fiskar",
        "content": """Fiskar (Pisces) är en grupp vattenlevande ryggradsdjur med fenor, som indelas i benfiskar, broskfiskar och käklösa fiskar. De flesta arter andas med gälar och är växelvarma. Undantaget är lungfiskar. Eftersom landryggradsdjuren släktskapsmässigt är en typ av kvastfeniga fiskar men inte klassificeras som fiskar är begreppet "fiskar" parafyletiskt. Vetenskapen om fiskar kallas iktyologi.""",
    },
    {
        "title": "Krabba",
        "content": """Krabbor (Brachyura) är en delordning av vattenlevande kräftdjur. Vissa arter fiskas som mat, ofta ansedda som delikatesser. Krabbor har tio ben varav det första paret bär gripklor.""",
    },
]

vector_db["articals"].add(articles_data)

AddResult(version=2)

In [18]:
vector_db["articals"].to_pandas()

    title                                            content
0  Fiskar  Fiskar (Pisces) är en grupp vattenlevande rygg...
1  Krabba  Krabbor (Brachyura) är en delordning av vatten...

In [19]:
vector_db.drop_table("articals")

In [20]:
vector_db.list_tables()

ListTablesResponse(tables=['animals_text'], page_token=None)

In [21]:
vector_db["animals_text"].to_pandas()

                                            text              vector
0                     A small brown dog running.  [0.12, 0.85, 0.33]
1               A cat resting quietly on a sofa.    [0.4, 0.91, 0.1]
2          A large gray elephant drinking water.  [0.88, 0.22, 0.55]
3  A fast cheetah sprinting across the savannah.  [0.95, 0.12, 0.72]
4         A colorful parrot perched on a branch.  [0.25, 0.66, 0.81]
5                  A frog sitting on a lily pad.  [0.14, 0.44, 0.27]
6              A panda eating bamboo peacefully.  [0.51, 0.37, 0.82]
7               A lion roaring loudly on a rock.  [0.93, 0.18, 0.41]

In [22]:
query_vector = [0.5, 0.3, 0.9] 
vector_db["animals_text"].search(query_vector).to_pandas()

,text,vector,_distance
0,A panda eating bamboo peacefully.,"[0.51, 0.37, 0.82]",0.0114
1,A colorful parrot perched on a branch.,"[0.25, 0.66, 0.81]",0.2002
2,A fast cheetah sprinting across the savannah.,"[0.95, 0.12, 0.72]",0.2673
3,A large gray elephant drinking water.,"[0.88, 0.22, 0.55]",0.2733
4,A lion roaring loudly on a rock.,"[0.93, 0.18, 0.41]",0.4394
5,A frog sitting on a lily pad.,"[0.14, 0.44, 0.27]",0.5461
6,A small brown dog running.,"[0.12, 0.85, 0.33]",0.7718
7,A cat resting quietly on a sofa.,"[0.4, 0.91, 0.1]",1.0221

In [24]:
from lancedb.embeddings import get_registry

embedding_model = get_registry().get("cohere").create(name = "embed-multilingual-v3.0")

embedding_model.ndims()

1024

In [25]:
from lancedb.pydantic import Vector

class JokesModel(LanceModel):
    joke: str = embedding_model.SourceField()
    emdbedding: Vector(embedding_model.ndims()) = embedding_model.VectorField() 

vector_db.create_table("jokes", schema=JokesModel, exist_ok=True)

vector_db["jokes"]

LanceTable(name='jokes', version=1, _conn=LanceDBConnection(uri='c:\\Users\\alici\\moln_mlpos\\code_along_moln_repo\\lecktion_6\\knowled_base'))

In [39]:
import pandas as pd
with open("jokes.json", encoding="utf8") as file:
    joke_data = json.load(file)

df_joke = pd.DataFrame(joke_data)
df_joke.head()

                                                joke
0  Parallel lines have so much in common—it’s sad...
1  ETL stands for “Extract, Transform, Leave for ...
2  What do you call a snake that runs your script...
3  Gold walks into a bar. The bartender says, “Au...
4   C# devs don’t argue; they just throw exceptions.

In [40]:
from dotenv import load_dotenv

load_dotenv()

vector_db["jokes"].add(df_joke)

AddResult(version=2)

In [41]:
vector_db["jokes"].to_pandas()

,joke,emdbedding
0,Parallel lines have so much in common—it’s sad...,"[-0.0032196045, 0.0011167526, -0.014953613, 0...."
1,"ETL stands for “Extract, Transform, Leave for ...","[0.012634277, 0.005268097, -0.09136963, 0.0809..."
2,What do you call a snake that runs your script...,"[0.019165039, 0.044677734, -0.021530151, 0.028..."
3,"Gold walks into a bar. The bartender says, “Au...","[0.019866943, 0.05999756, 0.012702942, 0.02343..."
4,C# devs don’t argue; they just throw exceptions.,"[0.013122559, 0.002374649, -0.05706787, 0.0608..."
5,I asked the data lake if it had my file. It sa...,"[-0.025970459, 0.0035209656, -0.061584473, 0.0..."
6,My math teacher said I’m average… how mean!,"[-0.0026016235, 0.03112793, 0.013343811, 0.030..."
7,Python is so friendly even whitespace gets a say.,"[0.0146484375, 0.016906738, -0.0026435852, 0.0..."
8,The C# compiler walked into a bar. The bartend...,"[0.0038490295, 0.006790161, -0.0769043, 0.0265..."
9,Never trust an atom—they make up everything.,"[-0.008956909, 0.003440857, -0.020614624, 0.04..."
10,Why was the equal sign so humble? It knew it w...,"[0.017501831, 0.021377563, -0.012313843, 0.070..."
11,My Python code works on the first try… said no...,"[0.02017212, 0.035736084, -0.008163452, 0.0485..."
12,Why did the chemist ground his kids? Because t...,"[-0.008056641, 0.031555176, -0.019454956, 0.01..."
13,"Our data pipeline broke… but don't worry, it w...","[-0.009239197, -0.011238098, -0.046722412, 0.0..."
14,C# programmers love coffee—they're always work...,"[-0.00541687, 0.0017910004, -0.060943604, 0.03..."
15,I told a chemistry joke… there was no reaction.,"[-0.03274536, 0.018218994, 0.039276123, 0.0012..."
16,Python devs never get lost—they always know th...,"[0.017852783, 0.026443481, -0.03829956, 0.0384..."
17,"Data engineer motto: If it works, don’t touch ...","[0.040740967, 0.007030487, -0.046173096, 0.098..."
18,Why’s 6 afraid of 7? Because 7 8 9.,"[0.005886078, 0.020553589, -0.0031318665, 0.01..."
19,I put “root beer” in a square glass… now it’s ...,"[0.008476257, 0.026138306, 0.046020508, 0.0015..."
20,Why do data engineers hate nature? Too many un...,"[0.039031982, 0.06201172, -0.02418518, 0.05044..."
21,Oxygen and Magnesium got together—OMg!,"[-0.04119873, -0.004600525, 0.007701874, 0.006..."
22,Why did the Python programmer get bitten? Beca...,"[0.012016296, 0.057678223, -0.0284729, 0.01250..."
23,I tried to explain async/await to my friend… n...,"[0.0028648376, 0.007926941, -0.016326904, 0.00..."
24,Chemists have all the solutions… mostly in bea...,"[0.0013589859, 0.03086853, -0.0012874603, 0.02..."
25,"Dear algebra, please stop asking us to find yo...","[0.011245728, 0.0046691895, -0.018936157, 0.06..."
26,"My pipeline failed again, so I’m logging out—l...","[0.0029716492, 0.002773285, -0.0748291, 0.0682..."
27,Why did the C# developer go broke? He kept usi...,"[0.028945923, 0.03753662, -0.03363037, 0.07330..."
28,Why is C# like a musical? It has so many classes.,"[-0.019012451, -0.016098022, -0.049621582, 0.0..."
29,Python devs don’t need therapy—they already im...,"[-0.0014638901, 0.018875122, 0.0059280396, 0.0..."